version: "3.8"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static_data:/vol/web
    env_file:
      - .env
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:15.4
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      interval: 10s
      retries: 5
      start_period: 10s
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 4g
        reservations:
          cpus: '0.25'
          memory: 2g

  proxy:
    build:
      context: ./proxy
    env_file:
      - .env
    restart: always
    depends_on:
      - app
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/static

volumes:
  postgres_data:
  static_data: